name: MyTest

on:
  workflow_dispatch:
  push:
    branches: [ new-index-test2 ]
  pull_request:
    types: [opened, synchronize, ready_for_review]
  merge_group:
# Cancel builds if a new commit is pushed, except on master
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: configure Pagefile
        if: matrix.os == 'windows-latest'
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Run linting
        run: |
          chmod +x gradlew
          ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew test --info