name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  qodana:
    name: Run Qodana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
      - uses: docker://jetbrains/qodana-jvm
        with:
          # https://github.com/JetBrains/qodana-action/blob/main/run_qodana.sh
          args: --cache-dir=/github/home/cache --results-dir=/github/workspace/qodana --save-report --report-dir=/github/workspace/qodana/report
      - uses: actions/upload-artifact@v2
        if: always()
        # To view the report: https://www.jetbrains.com/help/qodana/html-report.html
        with:
          path: qodana
      # https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/validation-cicd.html#example-setup-for-github-actions
      - name: Upload SARIF report to GitHub
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: /github/workspace/qodana/report/results/qodana.sarif.json
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Run linting
      run: |
        chmod +x gradlew
        ./gradlew ktlintCheck
    - name: Run tests
      run: ./gradlew check koverReport
    - name: Upload coverage report
      if: success() && matrix.os == 'ubuntu-latest'
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}